services:
  promptarchive:
    image: promptarchive
    depends_on:
      - postgres
      - minio
    build:
      context: .
    ports:
      - 80:80
    networks:
      - promptarchive
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres; Port=5432; Database=PromptArchive; Username=postgres; Password=postgres;
      Storage__Type: S3
      Storage__S3__BucketName: promptarchive
      Storage__S3__Region: eu-west-1
      Storage__S3__AccessKey: promptarchive
      Storage__S3__SecretKey: promptarchive
      Storage__S3__BaseUrl: minio:9000
      Storage__S3__Secure: false
      Storage__S3__ForcePathStyle: true
      InitialUser__Email: "admin@admin.com"
      InitialUser__Username: "Admin"
      InitialUser__Password: "Admin@1234"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: PromptArchive
    networks:
      - promptarchive
    volumes:
      - promptarchive-db:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio
    ports:
      - 9011:9001
    networks:
      - promptarchive
    environment:
      MINIO_ROOT_USER: "promptarchive"
      MINIO_ROOT_PASSWORD: "promptarchive"
    volumes:
      - promptarchive-minio:/data
    command: server /data --console-address ":9001"

volumes:
  promptarchive-db:
  promptarchive-minio:
   
networks:
  promptarchive:
