# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: PromptArchive
    ports:
      - "5432:5432"
    volumes:
      - promptarchive-pg-data:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: "promptarchive"
      MINIO_ROOT_PASSWORD: "promptarchive"
    volumes:
      - promptarchive-minio-data:/data
    command: server /data --console-address ":9001"
volumes:
  promptarchive-pg-data:
  promptarchive-minio-data:

